export interface Product {
  id: string;
  name: string;
  price: number;
  description: string;
  category: "keychain" | "flower-pot" | "bouquet" | "flower";
  image: string;
}

export const products: Product[] = [
  {
    id: "sunflower-bouquet",
    name: "Sunflower Bouquet",
    price: 499,
    description: "A beautiful wrapped bouquet of two handmade crochet sunflowers with green stems and a satin ribbon.",
    category: "bouquet",
    image: "/images/sunflower-bouquet.jpg",
  },
  {
    id: "sunflower-single",
    name: "Giant Sunflower",
    price: 299,
    description: "A single oversized crochet sunflower with rich orange petals and a detailed brown center.",
    category: "bouquet",
    image: "/images/sunflower-single.jpg",
  },
  {
    id: "sunflower-stems",
    name: "Sunflower Stems",
    price: 399,
    description: "A pair of crochet sunflower stems with leaves — perfect for placing in a vase.",
    category: "flower-pot",
    image: "/images/sunflower-stems.jpg",
  },
  {
    id: "bunny-flower",
    name: "Bunny Flower",
    price: 249,
    description: "An adorable crochet flower with a cute bunny face and carrot crown. A perfect gift for kids!",
    category: "keychain",
    image: "/images/bunny-flower.jpg",
  },
  {
    id: "rose-bouquet",
    name: "Rose & Tulip Bouquet",
    price: 699,
    description: "A stunning bouquet of handmade red roses, pink tulips, and a white rose. A gift that lasts forever.",
    category: "bouquet",
    image: "/images/rose-bouquet.jpg",
  },
  {
    id: "red-tulips",
    name: "Red Tulips",
    price: 399,
    description: "Vibrant red crochet tulips with green leaves — bold, beautiful, and everlasting.",
    category: "bouquet",
    image: "/images/red-tulips.jpg",
  },
  {
    id: "pink-tulips",
    name: "Pink Tulips",
    price: 399,
    description: "Soft pink crochet tulips with green stems — a delicate and charming bouquet.",
    category: "bouquet",
    image: "/images/pink-tulips.jpg",
  },
  {
    id: "calla-lily",
    name: "Calla Lily Stems",
    price: 449,
    description: "Elegant white crochet calla lilies with bright orange stamens — timeless and graceful.",
    category: "flower-pot",
    image: "/images/calla-lily.jpg",
  },
  {
    id: "single-red-rose",
    name: "Single Red Rose",
    price: 199,
    description: "A beautifully wrapped single crochet red rose with a satin ribbon bow — a classic romantic gift.",
    category: "bouquet",
    image: "/images/single-red-rose.png",
  },
  {
    id: "red-rose-bouquet",
    name: "Red Rose Bouquet",
    price: 799,
    description: "A stunning bouquet of three handmade crochet red roses wrapped in elegant black paper with a green satin bow.",
    category: "bouquet",
    image: "/images/red-rose-bouquet.png",
  },
  {
    id: "heart-keychain",
    name: "Heart Keychain",
    price: 149,
    description: "Adorable crochet heart keychain in red and pink — a sweet everyday accessory or gift.",
    category: "keychain",
    image: "/images/heart-keychain.png",
  },
  {
    id: "bear-keychain",
    name: "Bear Couple Keychain",
    price: 199,
    description: "A pair of adorable crochet teddy bears with red scarves — perfect matching keychains for couples.",
    category: "keychain",
    image: "/images/bear-keychain.png",
  },
  {
    id: "totoro-keychain",
    name: "Totoro Keychain",
    price: 200,
    description: "A cute crochet Totoro with a green leaf on its head — a must-have for Studio Ghibli fans.",
    category: "keychain",
    image: "/images/totoro-keychain.jpg",
  },
  {
    id: "coffee-cup-keychain",
    name: "Coffee Cup Keychain",
    price: 180,
    description: "A tiny crochet coffee cup with a happy face — the cutest companion for coffee lovers.",
    category: "keychain",
    image: "/images/coffee-cup-keychain.jpg",
  },
  {
    id: "bee-keychain",
    name: "Bee Keychain",
    price: 160,
    description: "A cheerful crochet bee with fluffy white wings — sweet, buzzy, and irresistibly cute.",
    category: "keychain",
    image: "/images/bee-keychain.jpg",
  },
  {
    id: "turtle-keychain",
    name: "Turtle Keychain",
    price: 179,
    description: "A sweet crochet turtle with a green shell and a tiny red flower — charming and detailed.",
    category: "keychain",
    image: "/images/turtle-keychain.jpg",
  },
  {
    id: "tulip-keychain",
    name: "Tulip Bunch Keychain",
    price: 199,
    description: "A colorful cluster of mini crochet tulips in pink, yellow, and white with green stems.",
    category: "keychain",
    image: "/images/tulip-keychain.jpg",
  },
  {
    id: "sunflower-keychain",
    name: "Sunflower Keychain",
    price: 150,
    description: "A pair of bright crochet sunflowers with a green leaf — a cheerful accessory for your keys.",
    category: "keychain",
    image: "/images/sunflower-keychain.jpg",
  },
  {
    id: "penguin-keychain",
    name: "Penguin Keychain",
    price: 180,
    description: "An adorable blue crochet penguin with a yellow beak — a tiny friend to carry everywhere.",
    category: "keychain",
    image: "/images/penguin-keychain.jpg",
  },
];
